name: pull_request_target-unassigned

on:
  pull_request_target:
    types: [unassigned]

jobs:
  foo:
    name: pull_request_target-unassigned
    runs-on: ubuntu-latest
    steps:
      - name: Event context info
        run: |
          cat <<'EOF'
          github: ${{toJSON(github)}}
          env: ${{toJSON(env)}}
          vars: ${{toJSON(vars)}}
          job: ${{toJSON(job)}}
          steps: ${{toJSON(steps)}}
          runner: ${{toJSON(runner)}}
          secrets: ${{toJSON(secrets)}}
          strategy: ${{toJSON(strategy)}}
          matrix: ${{toJSON(matrix)}}
          needs: ${{toJSON(needs)}}
          inputs: ${{toJSON(inputs)}}
          EOF
      - name: Dump environment
        run: env
